/*
* AMRIT – Accessible Medical Records via Integrated Technology 
* Integrated EHR (Electronic Health Records) Solution 
*
* Copyright (C) "Piramal Swasthya Management and Research Institute" 
*
* This file is part of AMRIT.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see https://www.gnu.org/licenses/.
*/

package com.iemr.common.service.videocall;

import com.iemr.common.model.videocall.UpdateCallRequest;
import com.iemr.common.model.videocall.VideoCallRequest;

public interface VideoCallService {

	 public String generateMeetingLink() throws Exception;

	 public String sendMeetingLink(VideoCallRequest request) throws Exception;

	 public String updateCallStatus(UpdateCallRequest request) throws Exception;

	 /**
	  * Resolve the short slug carried in the SMS link (the value after "?m=")
	  * into the full Jitsi URL with a freshly minted JWT appended.
	  * Called by the public redirect endpoint that the Jitsi host's nginx
	  * proxies "/?m=&lt;slug&gt;" requests to.
	  *
	  * @param slug the random slug originally generated by {@link #generateMeetingLink()}
	  * @return absolute URL of the form
	  *         https://&lt;jitsi.domain&gt;/&lt;jitsi.room.prefix&gt;&lt;slug&gt;?jwt=&lt;token&gt;
	  */
	 public String resolveMeetingLink(String slug) throws Exception;

	 /**
	  * Generate a moderator JWT URL for the agent/associate so they can join
	  * the Jitsi room with "End Meeting for All" privileges.
	  *
	  * @param slug      the meeting slug (value after "m=" in the meeting link)
	  * @param agentName display name for the agent in the Jitsi UI
	  * @param agentEmail agent email (used for Jitsi avatar / gravatar)
	  * @return absolute Jitsi URL with moderator JWT appended
	  */
	 public String generateAgentToken(String slug, String agentName, String agentEmail) throws Exception;
}
