<<<<<<<< HEAD:.github/workflows/package.yml
name: Package

on:
  push:
    branches: [ "develop"]
    paths-ignore:
     - target/**
     
  pull_request:
     branches: [ "develop" ]
     paths-ignore:
     - target/**
     
env:
  ENV_VAR: test

jobs:
  Package-test:
========
name: Static Code Analysis and Packaging
on:
  push:
    branches: [ "master","develop" ]
    
jobs:
  CodeQL:
>>>>>>>> 2c9c4f37f670158e36f1413a3817860f795b13db:.github/workflows/sast-and-package.yml
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
    steps:
    
    - name: Checkout code 
      uses: actions/checkout@v2
<<<<<<<< HEAD:.github/workflows/package.yml
      
========
>>>>>>>> 2c9c4f37f670158e36f1413a3817860f795b13db:.github/workflows/sast-and-package.yml
    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
<<<<<<<< HEAD:.github/workflows/package.yml
        
    - name: Build with Maven
      run: mvn clean install -DENV_VAR=${{ env.ENV_VAR }}
      
    - name: Build WAR file
      run: mvn -B package --file pom.xml
      
========
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: Java    
    - name: Build with Maven
      run: mvn clean install
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: Java   
    
  Packaging:
    needs: codeql
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
    - name: Create WAR file 
      run: mvn -B package --file pom.xml
>>>>>>>> 2c9c4f37f670158e36f1413a3817860f795b13db:.github/workflows/sast-and-package.yml
    - name: Upload WAR file as artifact
      uses: actions/upload-artifact@v2 
      with:
        name: Common-API
<<<<<<<< HEAD:.github/workflows/package.yml
        path: target/commonapi-v1.0.war
========
        path: target/commonapi-v1.0.war  
>>>>>>>> 2c9c4f37f670158e36f1413a3817860f795b13db:.github/workflows/sast-and-package.yml
